### PR TITLE
(feature:new_strapi_quemsomos)

### PR DESCRIPTION
**Pull request by claraabk**
## What I did

- Created a content type on Strapi to " Quem somos " section 
- Added to api paste
  - Created a single type content on Strapi containing images and texts
  

## How to test

1. Open the terminal and go to the folder of this project

1. In terminal:
   1. `git checkout develop`
   1. `git pull`
   1. `git checkout feature/strapi_add_quemsomos`
   1. `git pull origin feature/strapi_add_quemsomos`
   1. `yarn install`
   1. `yarn develop`

1. In your browser go to http://localhost:3000/<route>

1. In VScode open the folder of the project`

1. Things to do during the code:

   - Open insomnia and postbird to test the requisitions needed

1. Read the changed files section on GitHub

1. Test the things that you think are worth testing, even the ones that are not in this description

&nbsp;

---

### CODE REVIEW

**Review by GUIBA4 — APPROVED** [review]
Great job

**Review by gabrielapinheiroc — APPROVED** [review]
everything okay

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
It's very greate, but if you can change the position of text and images to look more like the mockup

**Comment by GUIBA4** [comment]
> Great job

**Pull request closed without merging**
